# Generated by Django 4.2.6 on 2023-11-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_number",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(max_length=40)),
                ("max_numb_students", models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_name", models.CharField(max_length=50)),
                ("courses", models.ManyToManyField(to="schedule.course")),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "ins_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("ins_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingTime",
            fields=[
                (
                    "meet_id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                (
                    "meet_time",
                    models.CharField(
                        choices=[
                            ("8:30 - 11:30", "8:30 - 11:30"),
                            ("11:45 - 2:45", "11:45 - 2:45"),
                            ("3:00 - 6:00", "3:00 - 6:00"),
                            ("6:30 - 9:30", "6:30 - 9:30"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=6)),
                ("seating_capacity", models.IntegerField(default=0)),
                ("room_type", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "section_id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("num_class_in_week", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.department",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.instructor",
                    ),
                ),
                (
                    "meeting_time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.meetingtime",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(to="schedule.instructor"),
        ),
    ]
