# Generated by Django 4.2.6 on 2023-11-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_number",
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
