# Generated by Django 5.0 on 2024-01-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=255)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='instructorpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='max_sessions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instructorpreference',
            name='max_classes_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instructorpreference',
            name='preferred_courses',
            field=models.ManyToManyField(to='schedule.course'),
        ),
        migrations.AddField(
            model_name='instructorpreference',
            name='preferred_days',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instructorpreference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.instructor')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.meetingtime')),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RemoveField(
            model_name='instructorpreference',
            name='course',
        ),
        migrations.RemoveField(
            model_name='instructorpreference',
            name='day',
        ),
        migrations.RemoveField(
            model_name='instructorpreference',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
