# Generated by Django 5.0 on 2024-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_meetingtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='classrooms',
            field=models.ManyToManyField(to='schedule.classroom'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='instructors',
            field=models.ManyToManyField(to='schedule.instructor'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='meeting_times',
            field=models.ManyToManyField(to='schedule.meetingtime'),
        ),
    ]
